# Generated by Django 5.2.9 on 2025-12-11 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField(help_text='GitHub repository URL that was scanned', max_length=500)),
                ('repository_name', models.CharField(blank=True, help_text='Repository name (owner/repo)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the scan', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the scan started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the scan completed', null=True)),
                ('duration_ms', models.IntegerField(default=0, help_text='Scan duration in milliseconds')),
                ('files_scanned', models.IntegerField(default=0, help_text='Number of files scanned')),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Full scan results in JSON format')),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan failed')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the scan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan History',
                'verbose_name_plural': 'Scan Histories',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='security_sc_user_id_f43182_idx'), models.Index(fields=['repository_url'], name='security_sc_reposit_d0688a_idx'), models.Index(fields=['status'], name='security_sc_status_90e7b4_idx')],
            },
        ),
    ]
